### ISSUE TITLE
rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by Megumiiiiii** [CESSProject/cess-nodeadm#11]
i try both `v0.4.2` and `v0.4.3`, non of them work. i try to change RPC URL to `wss://testnet-rpc0.cess.cloud/ws/` didn't work too

![Screenshot_20230904-142122](https://github.com/CESSProject/cess-nodeadm/assets/98658943/79292568-4c8b-4e11-bf08-4ab3a00b47ab)

**Comment by 0xbillw** [comment]
Thank you very much for your feedback!

This issue should be a problem with our `Tee Worker` server.
Currently, it should be fixed.
You can continue to observe. If there are still issues, please continue to provide feedback. 

Thank you!

**Comment by Megumiiiiii** [comment]
![Screenshot_33](https://github.com/CESSProject/cess-nodeadm/assets/98658943/f564f070-31f8-408e-b7d9-1584b630d543)
![Screenshot_34](https://github.com/CESSProject/cess-nodeadm/assets/98658943/85397ea9-6dca-4085-9648-4c66e778bf10)

Alright, new issue. automatically use `devnet` and can't connect to boot node. `tags v0.4.4`

**Comment by Megumiiiiii** [comment]
![Screenshot_52](https://github.com/CESSProject/cess-nodeadm/assets/98658943/e8d29e50-0808-41ef-956e-b764ca5c787e)
changed to testnet, and there are no finalized blocks

**Comment by 0xbillw** [comment]
I'm sorry our Wiki documentation doesn't make that clear.
CESS currently has *devnet* and *testnet*, switch to *testnet* using `cess profile testnet`.
You can use `cess -h` to see how to use it.

**Comment by Megumiiiiii** [comment]
Alright, now it works! Cool!

```
++ 2023-09-11 08:36:01 Chain network: cess-testnet
++ 2023-09-11 08:36:01 P2P network: cess-testnet
OK 2023-09-11 08:36:01 Synchronization main chain completed: 3140
++ 2023-09-11 08:36:03 Successfully found 12D3KooWLtpEaPbJhTyC8qoRp8PrjHy4ou7TCSY3XEtzNsh4Jatb for registration
++ 2023-09-11 08:36:06 Workspace: /opt/bucket-disk/cXjxBS2YV2z2EFgyD5UeYFmg27ms26bWrQ2Sp8QtWmZWUiiQ3/bucket
OK 2023-09-11 08:36:06 Start successfully
```
