### ISSUE TITLE
open /opt/bucket-disk/cXhZrTemhkjsKW1Tn2RBxnMjG7kzbyjYuPfbABrFHUBQ48bed/bucket/.podr2pubkey: no such file or directory

### ISSUE THREAD

**Issue by iamhuoge** [CESSProject/cess-nodeadm#23]
![image](https://github.com/CESSProject/cess-nodeadm/assets/28769166/89f36be1-40ee-4d91-ae9b-ef5a7398789f)

**Comment by iamhuoge** [comment]
![image](https://github.com/CESSProject/cess-nodeadm/assets/28769166/0200fd4b-bac9-4e0e-80d4-e949e4c14c80)

**Comment by 0xbillw** [comment]
@AstaFrode

**Comment by AstaFrode** [comment]
@iamhuoge It has something to do with your network. Try rebooting.
