### ISSUE TITLE
A little problem with the Storage Node Docs

### ISSUE THREAD

**Issue by wshl25** [CESSProject/cess-nodeadm#26]
https://docs.cess.cloud/core/storage-miner/running#check-your-storage-miner-status-on-chain
![1708940346804](https://github.com/CESSProject/cess-nodeadm/assets/12468851/471ef684-0a9d-485d-8cc0-746fe8c2d498)
Hi，Maybe,The query button is on the right, not the left.

**Comment by jiuquxzy** [comment]
> https://docs.cess.cloud/core/storage-miner/running#check-your-storage-miner-status-on-chain ![1708940346804](https://private-user-images.githubusercontent.com/12468851/307736998-471ef684-0a9d-485d-8cc0-746fe8c2d498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDU2MzcsIm5iZiI6MTcwOTYwNTMzNywicGF0aCI6Ii8xMjQ2ODg1MS8zMDc3MzY5OTgtNDcxZWY2ODQtMGE5ZC00ODVkLThjYzAtNzQ2ZmU4YzJkNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAyMjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNDc2NzRkYTk2OGYwODFmNDI5NmIyMTg4OWM2YmYzMjVmNDljNThlN2I4NjkwNDQ4NGMwZGM4MWE3N2Y2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pxm_l6QG9FRVtkZXCfV6vnD75yCPSrEXXoS5e2g-pg4) Hi，Maybe,The query button is on the right, not the left.

Thank you, sir
