### ISSUE TITLE
I had a bug and want to report it

### ISSUE THREAD

**Issue by fishzone24** [CESSProject/cess-nodeadm#32]
hi there,
  I had several new storage nodes running yesterday. Everything was fine until the Nodes Syncing (I am pretty sure the installation progress is correct cause I have already had some server running and have the PowerG showing on your Google Sheet). I paste the bug report below:

---------------------------
  Version: 0.7.6-d2220c01057

   0: sp_panic_handler::set::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/alloc/src/boxed.rs:2021:9
      std::panicking::rust_panic_with_hook
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/std/src/panicking.rs:709:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/std/src/panicking.rs:597:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/std/src/sys_common/backtrace.rs:151:18
   4: rust_begin_unwind
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/std/src/panicking.rs:593:5
   5: core::panicking::panic_fmt
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/core/src/panicking.rs:67:14
   6: core::panicking::panic_display
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/core/src/panicking.rs:150:5
      core::panicking::panic_str
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/core/src/panicking.rs:134:5
      core::option::expect_failed
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/core/src/option.rs:1952:5
   7: core::option::Option<T>::expect
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/core/src/option.rs:898:21
      <std::time::Instant as core::ops::arith::Add<core::time::Duration>>::add
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/std/src/time.rs:408:33
   8: tokio::time::interval::Interval::poll_tick
   9: libp2p_mdns::behaviour::timer::tokio::<impl futures_core::stream::Stream for libp2p_mdns::behaviour::timer::Timer<tokio::time::interval::Interval>>::poll_next
  10: <libp2p_swarm::behaviour::toggle::Toggle<TBehaviour> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  11: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  12: <sc_network::behaviour::Behaviour<B> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  13: libp2p_swarm::Swarm<TBehaviour>::poll_next_event
  14: sc_network::service::NetworkWorker<B,H>::next_action::{{closure}}::{{closure}}::{{closure}}
  15: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  16: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
  17: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  18: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  19: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  20: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  21: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  22: tokio::runtime::park::CachedParkThread::block_on
  23: tokio::runtime::context::runtime::enter_runtime
  24: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  25: tokio::runtime::task::core::Core<T,S>::poll
  26: tokio::runtime::task::harness::Harness<T,S>::poll
  27: tokio::runtime::blocking::pool::Inner::run
  28: std::sys_common::backtrace::__rust_begin_short_backtrace
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/alloc/src/boxed.rs:2007:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/alloc/src/boxed.rs:2007:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/4c8bb79d9f565115637cc6da739f8389e79f3a29/library/std/src/sys/unix/thread.rs:108:17
  31: start_thread
  32: clone

Thread 'tokio-runtime-worker' panicked at 'overflow when adding duration to instant', library/std/src/time.rs:408

This is a bug. Please report it at:

        support.anonymous.an
-----------------------

BTW, the node version is 0.5.5 
the system info is hard to tell cause I had server VPS or dedicate server have the same bug report

**Comment by 0xbillw** [comment]
Thank you for reporting the bug issue.
This issue has been resolved in the next version.
